# **Introduction to NumPy**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object and selection of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, basic linear algebra, basic statistical operations, random simulation and much more.

To use NumPy package in your python application or notebook it must first be imported. You can use an alias to refer to the package throughout your application. It is convention to use "np" as a alias to the NumPy package.

In [2]:
import numpy as np

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

There are few things to remember when it comes to n-dimensional arrays:


1. NumPy arrays have a fixed size at creation.
2. The elements in a NumPy array are all required to be of the same data type.
3. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data.



## **1. What is an Array?**

Arrays are containers which are able to store more than one item at the same time. Specifically, they are an **ordered** collection of elements with every value being of the **same data type**.

Arrays are defined by their:

* **rank**: number of dimension of the array object.
* **shape**: size of each dimension.
* **dtype**: data type for all the elements in the array.






###*Examples*

In [4]:
#This code creates a 1-Dimensional Array and saves in a variable "a"
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)
int32
1


In [5]:
#This code creates a 2-Dimensional Array and saves in a variable "b"
b = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
print(b)
print(type(b))
print(b.shape)
print(b.dtype)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
(3, 4)
int32
2


In [7]:
#This code creates a 3-Dimensional Array and saves in a variable "c"
c = np.array([
              [[1, 2, 3, 4], 
               [5, 6, 7, 8], 
               [9, 10, 11, 12]],
              
              [[13, 14, 15, 16], 
               [17, 18, 19, 20], 
               [21, 22, 23, 24]]
             ])
print(c)
print(type(c))
print(c.shape)
print(c.dtype)
print(c.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
<class 'numpy.ndarray'>
(2, 3, 4)
int32
3


In [11]:
d = np.array(1)
print(type(d))
print(d.shape)
print(d.ndim)
print(d.dtype)

<class 'numpy.ndarray'>
()
0
int32


Array of different dimensions are named differently.

*   1-D Arrays are called **Vectors**
*   2-D Arrays are called **Metrices**
*   Any arrays aboye 2 dimensions are called **Tensors**

Dimension of an array is known as the **axis**



## **2. Creating Arrays**

### 2.1 numpy.array()

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [ ]:
#This code creates an 1-D array with the given list of values
my_array = np.array([3, 4, 5])
print(my_array)

[3 4 5]


### 2.2 numpy.zeros(shape)

You can create an array filled with 0's. Pass an integer to this function to specify number of items array will contain. Each element in the array is initialized with a floating value of 0.0

In [ ]:
#This code creates a 1-D array of size 6
my_array = np.zeros(6)
print(my_array)

[0. 0. 0. 0. 0. 0.]


### 2.3 numpy.ones(shape)

You can create an array filled with 1's. Pass an integer to this function to specify number of items array will contain. Each element in the array is initialized with a floating value of 1.0

In [13]:
#This code creates a 1-D array of size 5
my_array = np.ones(5)
print(my_array)

[1. 1. 1. 1. 1.]


### 2.4 numpy.arange(start, stop, step)

You can create an array filled with values within the s:pecified range. Keep a note that the value of the stop parameter is exclusive.

In [3]:
#create an array having values from 1 to 10
my_array = np.arange(1,11,1)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


### **Excercise**

Write a function that takes 2 arrays of same length filled with user defined values and check if they are elemet-wise equal. Element-wise equal arrays will have the same value on the same index.

For example array([1,2,3,4]) and array([1,2,3,4]) are element-wise equal while array([1,2,3,4]) and array([1,2,3,5]) is not element-wise equal.

The funtion should return boolean false if the arrays are element-wise not equal or boolean true if if the arrays are element-wise equal.

In [12]:
def ElementWiseEqual(arr1, arr2):
  # Start your code here



  # End you code here

In [ ]:
arr1 = []
arr2 = []

array_length = int(input("Enter array length: "))

for i in range(array_length):
  num1 = int(input(f"Enter {i+1} number for array 1: "))
  num2 = int(input(f"Enter {i+1} number for array 2: "))
  arr1.append(num1)
  arr2.append(num2)

arr1 = np.array(arr1)
arr2 = np.array(arr2)

print(ElementWiseEqual(arr1, arr2))

## **3. Array Indexing and Slicing**

Elements in an array are ordered. Therefore you can access them using indexing and slicing methods that were previously used in lists.

**Remember index of an array starts from 0**

In [12]:
array = np.array([1,2,3,4,5,6])

#print(array[0])
# print(array[0:3])
# sub_arr = array[0:3]
# print(type(sub_arr))
# print(array[1:])
# print(array[:4])
# print(array[:-2])
# print(array[:-2])


An addition to normal retrival methods, conditions can also be used to extract data from an array.

In [16]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array[array % 3 == 0]

array([ 3,  6,  9, 12])

Multiple conditions can be used in conjuction to create a more complex condition

In [27]:
elements = array[(array>2) & (array<11) & (array % 3 == 0)]
print(elements)

[3 6 9]


## **4. Array Shape and Size**

There are few properties of an array that you can access to get more information about the array's structure. There properties are:

1.   **ndarray.ndim**: will tell you the number of axes, or dimensions, of the array.
2.   **ndarray.size**: will tell you the total number of elements of the array.
3.   **ndarray.shape**: will display a tuple of integers that indicate the number of elements stored along each dimension of the array.



###*Examples*

In [2]:
#Create a Matrix of type integer

my_array = np.array([[0, 1, 2, 3],
                     [4, 5, 6, 7],
                     [0, 1, 2, 3],
                     [4, 5, 6, 7]])

In [3]:
my_array.ndim

2

In [4]:
my_array.size

16

In [5]:
my_array.shape

(4, 4)

Numpy also allows modification of an array's shape after it has been created. This can be achived by **ndarray.reshape()**

In [11]:
data = np.array([1,2,3,4,5,6])
print(data.shape)
print(data.ndim)

(6,)
1


In [12]:
reshaped_data = data.reshape(2,3)
print(reshaped_data)
print(reshaped_data.ndim)
print(reshaped_data.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [17]:
my_arr = np.array([[ 2, 3, 4], [ 5, 6, 7], [ 8, 9, 10]])
print(my_arr)
print(my_arr.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)


In [18]:
reshape_arr = my_arr.reshape(1,9)[0]
print(reshape_arr)
print(reshape_arr.shape)

[ 2  3  4  5  6  7  8  9 10]
(9,)


In [19]:
reshape_arr = my_arr.reshape(1,9).squeeze()
print(reshape_arr)
print(reshape_arr.shape)

[ 2  3  4  5  6  7  8  9 10]
(9,)


In [41]:
n_arr = np.ones(shape=(1, 3, 8))
print(n_arr)
print(n_arr.shape)
print()
sq_arr = n_arr.squeeze()
print(sq_arr)
print(sq_arr.shape)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]
(1, 3, 8)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
(3, 8)


In [47]:
n_arr = np.ones(shape=(3, 8))
re_arr = n_arr.reshape(2,5) # conflict on number of values
print(re_arr)

ValueError: cannot reshape array of size 24 into shape (2,5)

### **Excercise**

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [25]:
# start your code here
arr = np.arange(2,11,1)
print(arr)
print(arr.shape)
# end your code here

[ 2  3  4  5  6  7  8  9 10]
(9,)


## **5. Sorting and Concatenating Array Elements**

### 3.1 Sorting elements in Array

Sorting elements in assending order is simple with np.sort(). You can specify the axis, kind, and order when you call the function. Note that np.sort() only sorts elements in ascending order.

In [7]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr2 = np.sort(arr)
print(arr2)

[1 2 3 4 5 6 7 8]


### **Excercise**

Create a function that takes an array as a parameter and returns the sorted array in decending order.

Hint: **numpy.flip(array_object)** can be used to reverse an array.

In [ ]:
#can be given as a task
arr3 = np.flip(arr2)
print(arr3)

[8 7 6 5 4 3 2 1]


In [48]:
def SortArrayDecending(arr):
  # start your code here
    pass
  # end your code here

In [ ]:
arr1 = []

array_length = int(input("Enter array length: "))

for i in range(array_length):
  num1 = int(input(f"Enter {i+1} number for array 1: "))
  arr1.append(num1)

arr1 = np.array(arr1)

print(SortArrayDecending(arr1))

### 3.2 Concatenating Arrays

You can join elements to 2 or more arrays using numpy.concatenate()

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


It is important to remember that the arrays that are to be concatenated must be passed in as a tuple like (array1, array2).

Higher dimensional arrays can also be concatenated by specifying the axis property of np.concatenate(). Doing this specifies which dimensions of the arrays are to be concatenated.

In [53]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a)
print(b)
c = np.concatenate((a,b), axis = 1)
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [59]:
arr1 = np.ones(shape=(2,3))
arr2 = np.ones(shape=(3,4))

print(arr1)
print()
print(arr2)


c = np.concatenate((arr1,arr2), axis = 0)

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

## **6. Array Operations**

### 6.1 Mathmatical Operations

In [73]:
#This creates 2 arrays
data = np.array([1, 2])
data2 = np.array([3, 4])
ones = np.ones(2, dtype=int)

In [67]:
print(data)
print(data * 2)

[1 2]
[2 4]


In [74]:
print(data)
print(ones)
print(data2)

[1 2]
[1 1]
[3 4]


In [77]:
#array addition
sum_array = data + data2 + ones

#array subtraction
sub_array = data - ones

#array multiplication
mul_array = data * ones

#array division
div_array = data / ones

In [78]:
print(sum_array)
print(sub_array)
print(mul_array)
print(div_array)

[5 7]
[0 1]
[1 2]
[1. 2.]


In [ ]:
#Code shows opertion of broadcast between vector (array) and scaler value
new_data = data * 2
print(new_data)

[2 4]


In [64]:
my_l = [1, 2, 3, 4]
for i in range(0, len(my_l)):
    my_l[i] = my_l[i] * 2
print(my_l)

[2, 4, 6, 8]


### 6.2 Statistical Operations

In [ ]:
#Declare and Initialize data
vector = np.array([1,2,3,4,5])
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
print(vector.sum())
print(matrix.sum(axis=0))

15
[12 15 18]


In [ ]:
print(vector.min())
print(matrix.min(axis=0))

1
[1 2 3]


In [ ]:
print(vector.prod())
print(matrix.prod(axis=0))

120
[ 28  80 162]


In [ ]:
print(vector.max())
print(matrix.max(axis=0))

5
[7 8 9]


In [ ]:
print(vector.mean())
print(matrix.mean(axis=0))

3.0
[4. 5. 6.]


In [ ]:
print(vector.std())
print(matrix.std(axis=0))

1.4142135623730951
[2.44948974 2.44948974 2.44948974]


### **Excercise**

Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

In [ ]:
# start your code here

# end your code here